# Generated by Django 5.0.2 on 2025-01-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_delivery_time_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="+0000000000", max_length=15),
        ),
    ]
