# Generated by Django 5.1.2 on 2024-11-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True),
        ),
    ]
